name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t devops-ninja .
          echo "IMAGE_ID=devops-ninja" >> $GITHUB_ENV

      - name: Install Trivy with cache
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          mkdir -p ~/.cache/trivy
          trivy --cache-dir ~/.cache/trivy --version

      - name: Scan image with Trivy
        id: trivy-scan
        run: |
          # Mise à jour de la DB avec cache
          trivy --cache-dir ~/.cache/trivy image --download-db-only
          
          # Analyse avec les scanners actuels
          trivy --cache-dir ~/.cache/trivy image \
            --scanners vuln \
            --format sarif \
            --output trivy-results.sarif \
            --severity CRITICAL,HIGH \
            --ignore-unfixed \
            ${{ env.IMAGE_ID }}
          
          # Analyse des résultats
          if [ -s trivy-results.sarif ]; then
            echo "VULNERABILITIES_FOUND=true" >> $GITHUB_ENV
            echo "::error::Critical vulnerabilities detected - see report"
            cat trivy-results.sarif | jq '.runs[0].results[] | select(.level == "error") | .message'
            exit 1
          fi

      - name: Upload Trivy report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.sarif

      - name: Login and Push
        if: env.VULNERABILITIES_FOUND != 'true'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag ${{ env.IMAGE_ID }} ghcr.io/matuidi1234/devops-ninja:latest
          docker push ghcr.io/matuidi1234/devops-ninja:latest