name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t devops-ninja .
          echo "IMAGE_ID=devops-ninja" >> $GITHUB_ENV

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy --version

      - name: Scan image with Trivy
        id: trivy-scan
        run: |
          # Analyse et génération du rapport
          trivy image \
            --security-checks vuln \
            --format sarif \
            --output trivy-results.sarif \
            --severity CRITICAL,HIGH \
            --ignore-unfixed \
            ${{ env.IMAGE_ID }}
          
          # Vérification des vulnérabilités critiques
          if grep -q '"level": "error"' trivy-results.sarif; then
            echo "VULNERABILITIES_FOUND=true" >> $GITHUB_ENV
            echo "::error::Critical vulnerabilities detected - blocking image push"
            exit 1  # Bloque immédiatement le workflow
          fi

      - name: Upload Trivy report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.sarif

      - name: Login to GitHub Container Registry
        if: env.VULNERABILITIES_FOUND != 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        if: env.VULNERABILITIES_FOUND != 'true'
        run: |
          docker tag ${{ env.IMAGE_ID }} ghcr.io/matuidi1234/devops-ninja:latest
          docker push ghcr.io/matuidi1234/devops-ninja:latest