name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/matuidi1234/devops-ninja:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy --version

      - name: Scan image with Trivy
        id: trivy-scan
        run: |
          trivy image \
            --security-checks vuln \
            --format sarif \
            --output trivy-results.sarif \
            --severity CRITICAL,HIGH \
            --ignore-unfixed \
            --exit-code 0 \  # Ne pas bloquer le workflow
            ghcr.io/matuidi1234/devops-ninja:latest
          
          # Vérifie manuellement les résultats
          if grep -q '"level": "error"' trivy-results.sarif; then
            echo "VULNERABILITIES_FOUND=true" >> $GITHUB_ENV
          fi

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.sarif

      - name: Fail if critical vulnerabilities found
        if: env.VULNERABILITIES_FOUND == 'true'
        run: |
          echo "::error::Critical vulnerabilities detected! Check Trivy report."
          exit 1

      - name: Push Docker image
        if: env.VULNERABILITIES_FOUND != 'true'
        run: |
          docker push ghcr.io/matuidi1234/devops-ninja:latest