name: Quality Check (Quête 3)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run npm audit
      run: |
        npm audit --audit-level=moderate || true
        echo "npm audit exit code: $?"
        # Le workflow échouera explicitement plus tard si nécessaire

    - name: Dependency Vulnerability Scan
      uses: actions/dependency-review-action@v3

    - name: Upload ESLint results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: eslint-results
        path: eslint-report.txt
        retention-days: 5

    - name: Fail if vulnerabilities found
      if: steps.audit.outcome == 'failure'
      run: |
        echo "::error::Critical vulnerabilities found in dependencies!"
        exit 1